[build]
  publish = "."
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[headers]]
  for = "/*"
  [headers.values]
    Service-Worker-Allowed = "/"
